gha: run on ubuntu-20.04
We require a newer systemd (currently) to build the `bus` bindings.
Notably, the version in 18.04 gets these two link errors:

           /home/runner/work/rust-systemd/rust-systemd/src/bus/mod.rs:1269:
undefined reference to `sd_bus_slot_set_destroy_callback'
          /home/runner/work/rust-systemd/rust-systemd/src/bus/mod.rs:1270:
undefined reference to `sd_bus_slot_set_floating'

We should consider looking into whether these can be avoided an provide
a usable API. Possible that `bus` could be subsetted. Minimally,
detecting the presense of these functions at configuration time and
avoiding emitting the rust definitions would help us get better error
messages (ie: at compile instead of at link).